flask_app/app.py
from flask import Flask
from flask_bootstrap import Bootstrap

from nav import nav
from routes import frontend
from flask_wtf.csrf import CSRFProtect

csrf = CSRFProtect()
server = Flask(__name__)
csrf.init_app(server)

Bootstrap(server)

server.register_blueprint(frontend)

# Because we're security-conscious developers, we also hard-code disabling
# the CDN support (this might become a default in later versions):
server.config["BOOTSTRAP_SERVE_LOCAL"] = True
server.config["SEND_FILE_MAX_AGE_DEFAULT"] = 0
server.config['UPLOAD_FOLDER'] = '/deploy/import_export_data/'
server.config['DB_HOSTNAME'] = 'db_server'

server.config.update(dict(
    SECRET_KEY="powerful secretkey",
    WTF_CSRF_SECRET_KEY="a csrf secret key"
))

# We initialize the navigation as well
nav.init_app(server)

flask_app/routes.py
# This contains our frontend; since it is a bit messy to use the @app.route
# decorator style when using application factories, all of our routes are
# inside blueprints. This is the front-facing blueprint.
#
# You can find out more about blueprints at
# http://flask.pocoo.org/docs/blueprints/
import time

import pandas as pd
from flask import Blueprint, Response, jsonify, render_template, request, current_app, send_file, flash
from flask_nav.elements import Navbar, View

from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed, FileRequired
from wtforms import SubmitField

from nav import nav
from pokemon_data_scraper.src.db.db_connector import DBHandler
from pokemon_data_scraper.src.db.db_schema import Collection
from pokemon_data_scraper.src.logger.logging import LOGGER
from pokemon_data_scraper.src.scraping.scrap_cards import main_card_fetching
from pokemon_data_scraper.src.scraping.scrap_extensions import main_computation

from werkzeug.utils import secure_filename

frontend = Blueprint("frontend", __name__)


# We're adding a navbar as well through flask-navbar. In our example, the
# navbar has an usual amount of Link-Elements, more commonly you will have a
# lot more View instances.
nav.register_element(
    "frontend_top",
    Navbar(View("Home", ".index"), View("Extensions", ".extensions_list"), View("All cards", ".cards_list"),
           View("Options", ".options")),
)


class UploadForm(FlaskForm):
    validators = [
        FileRequired(message='There was no file!'),
        FileAllowed(['csv'], message='Must be a csv file!')
    ]

    input_file = FileField('', validators=validators)
    submit = SubmitField(label="Upload")


@frontend.route("/")
def index():
    client = DBHandler(current_app.config['DB_HOSTNAME'])
    ownedNumber, total, percent = client.get_full_collection_progress()
    return render_template("index.html", ownedNumber=ownedNumber, total=total, percentage=percent)


@frontend.route("/extensions")
def extensions_list():
    return render_template("extension_page.html")


@frontend.route("/cards")
def cards_list():
    return render_template("card_page.html")


@frontend.route("/extension/<name_code>")
def extension_details(name_code: str):
    client = DBHandler(current_app.config['DB_HOSTNAME'])
    return render_template(
        "extension_details.html",
        ext_name=name_code.split("_")[1],
        ext_code=name_code.split("_")[0],
        ext=client.get_card_list_for_extension(name_code.split("_")[0]),
    )


@frontend.route("/data_post", methods=["POST"])
def data_post():
    # handle your database access, etc.
    LOGGER.error(f"Request is {request.json}")
    client = DBHandler(current_app.config['DB_HOSTNAME'])
    client.insert_owned_card(request.json)
    return "received"


@frontend.route("/options")
def options():
    return render_template("options.html", form = UploadForm())


@frontend.route("/log_extensions_stream", methods=["GET"])
def log_extensions_stream():
    """returns logging information"""

    def generate_log_extensions():
        with open("/deploy/flask_app/logs/logger-extensions-scraper.log") as f:
            while True:
                yield f.read()
                time.sleep(1)

    return Response(generate_log_extensions(), mimetype="text/plain", content_type="text/event-stream")


@frontend.route("/fetch_extensions", methods=["POST"])
def launch_fetching_extensions():
    LOGGER.info("We are starting to fetch extensions")
    main_computation()
    return ""


@frontend.route("/log_cards_stream", methods=["GET"])
def log_cards_stream():
    """returns logging information"""

    def generate_log_cards():
        with open("/deploy/flask_app/logs/logger-cards-scraper.log") as f:
            while True:
                yield f.read()
                time.sleep(1)

    return Response(generate_log_cards(), mimetype="text/plain", content_type="text/event-stream")


@frontend.route("/fetch_cards", methods=["POST"])
def launch_fetching_cards():
    LOGGER.info("We are starting to fetch cards")
    main_card_fetching()
    return ""


@frontend.route("/delete_ext", methods=["POST"])
def delete_ext():
    # handle your database access, etc.
    LOGGER.debug(f"Request is {request.json}")
    client = DBHandler(current_app.config['DB_HOSTNAME'])
    client.delete_extension(request.json)
    return "received"


@frontend.route("/extension_live_search", methods=["POST", "GET"])
def extension_live_search():
    client = DBHandler(current_app.config['DB_HOSTNAME'])
    if request.method == "POST":
        if request.form:
            search_word = request.form["query"]
            LOGGER.info(search_word)
            extensions_list = client.get_all_extensions_for_ui(value=search_word)
        else:
            extensions_list = client.get_all_extensions_for_ui(value="")

    return jsonify({"htmlresponse": render_template("extensions_list.html", extensions_df=extensions_list)})


@frontend.route("/cardlive_search", methods=["POST", "GET"])
def card_live_search():
    client = DBHandler(current_app.config['DB_HOSTNAME'])
    if request.method == "POST":
        if request.form:
            search_word = request.form["query"]
            LOGGER.info(search_word)
            cards = client.get_all_cards_for_ui(value=search_word)
        else:
            cards = client.get_all_cards_for_ui(value="")

    return jsonify({"htmlresponse": render_template("cards_list.html", cards=cards)})


@frontend.route("/export_data", methods=["GET"])
def export_data():
    client = DBHandler(current_app.config['DB_HOSTNAME'])
    filename = client.export_your_collection()
    return send_file(current_app.config['UPLOAD_FOLDER'] + filename, as_attachment=True)


@frontend.route('/uploader', methods=['POST'])
def uploader():
    client = DBHandler(current_app.config['DB_HOSTNAME'])
    form = UploadForm(request.files)
    if request.method == 'POST' and form.validate_on_submit():
        input_file = request.files['input_file']
        LOGGER.info(input_file)
        df = pd.read_csv(input_file)
        if set([Collection.CARD_NAME, Collection.CARD_NUMBER, Collection.CARD_EXTENSION_CODE]).issubset(set(df.columns)) and client.process_import(df):
            flash("Your export has been treated. Thank you!", "success")
            LOGGER.info(df)
        else:
            flash("The file has not the correct headers! ", "error")
    else:
        flash("This is not a correct format, or file", "error")

    return render_template("options.html", form=UploadForm())

flask_app/templates/card_page.html
{# This simple template derives from ``base.html``. See ``base.html`` for
more information about template inheritance. #}
{%- extends "base.html" %}

{# Loads some of the macros included with Flask-Bootstrap. We are using the
utils module here to automatically render Flask's flashed messages in a
bootstrap friendly manner #}
{% import "bootstrap/utils.html" as utils %}

{% block styles -%}
{{super()}}
<link rel="stylesheet" type="text/css"
      href="{{url_for('static', filename='styles/cards.css')}}">
{% endblock %}


{# Inside the ``content`` is where you should place most of your own stuff.
This will keep scripts at the page end and a navbar you add on later
intact. #}
{% block content %}
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script>
$(document).ready(function(){
  load_data();
  function load_data(query)
  {
    var csrf_token = "{{ csrf_token() }}";

    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrf_token);
            }
        }
    });
   $.ajax({
    url: "{{ url_for('frontend.card_live_search') }}",
    method:"POST",
    data:{'query': query},
    success:function(data)
    {
      $('#result').html(data);
      $("#result").append(data.htmlresponse);
    }
   });
  }
  $('#search_text').keyup(function(){
    var search = $(this).val();
    load_data(search);
  });
});

</script>

<div class="search-box">
    <div class="row">
        <div class="col-md-8 search-div">
            <h5>Search Cards</h5>
        </div>
        <div class="col-md-8 search-div">
            <input type="text" name="search_text" id="search_text" class="form-control"
                   placeholder="Search any cards (english or japanese name)">
        </div>
    </div>
</div>
<div id="result"></div>
{%- endblock %}

flask_app/templates/cards_list.html
{# This simple template derives from ``base.html``. See ``base.html`` for
more information about template inheritance. #}

{# Loads some of the macros included with Flask-Bootstrap. We are using the
utils module here to automatically render Flask's flashed messages in a
bootstrap friendly manner #}
{% import "bootstrap/utils.html" as utils %}

{% block styles -%}
<link rel="stylesheet" type="text/css"
      href="{{url_for('static', filename='styles/cards.css')}}">
{% endblock %}


{# Inside the ``content`` is where you should place most of your own stuff.
This will keep scripts at the page end and a navbar you add on later
intact. #}
{% block content %}

<div class="row">
       <div class="custom-align">
          <!-- Adding bootstrap table classes to style a table-->
          <table class="table table-hover table-striped text-center">
             <thead>
                <tr>
                   <th scope="col">Number</th>
                   <th scope="col">Name</th>
                    <th scope="col">Extension</th>
                    <th scope="col">Japanese Name</th>
                </tr>
             </thead>

             <tbody class="text-left">
               {% for odx, row in cards.iterrows() %}
               <tr>
                   <td> <a class="btn" rel="popover" data-img={{ row['cardImageUrl'] }}> {{ row['cardNumber'] }} </a></td>
                   {% if row['owned'] %}
                   <td><input type="checkbox" name="id" onChange="handleChange(this, '{{ row['cardName'] }}', {{ row['cardNumber'] }}, '{{ row['cardExtensionCode'] }}')" checked> {{ row['cardName'] }}</td>
                   {% else %}
                   <td><input type="checkbox" name="id" onChange="handleChange(this, '{{ row['cardName'] }}', {{ row['cardNumber'] }}, '{{ row['cardExtensionCode'] }}')"> {{ row['cardName'] }}</td>
                   {% endif %}
                   <td><a id="extension-title"
                                                    href="extension/{{ row['cardExtensionCode'] }}_{{ row['extensionName'] }}"
                                                    target="_blank"> {{ row['extensionName'] }} </a></td>
                   <td> <p>{{ row['cardJapaneseName'] }}</p></td>
               </tr>
               {% endfor %}
             </tbody>
          </table>
       </div>
</div>

<script>
   $('a[rel=popover]').popover({
   html: true,
   trigger: 'hover',
   placement: 'auto right',
   content: function(){return '<img src="'+$(this).data('img') + '" style="width:360px;height:500px;"/>';}
   });
</script>

<script type="text/javascript" src="http://code.jquery.com/jquery-3.4.1/jquery.min.js"></script>

<script type="text/javascript">

      function handleChange(sel, cardName, cardNumber, cardExtensionCode){
            var csrf_token = "{{ csrf_token() }}";

            $.ajaxSetup({
                beforeSend: function(xhr, settings) {
                    if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrf_token);
                    }
                }
            });
             $.ajax({
                 url: "{{ url_for('frontend.data_post') }}",
                 method: "POST",
                 contentType: "application/json",
                 dataType: 'json',                 data: JSON.stringify( {"cardName": cardName, "cardNumber": cardNumber, "cardExtensionCode": cardExtensionCode, "owned": sel.checked})
             });
         }

      function deleteExtension(extensionCode){
            var csrf_token = "{{ csrf_token() }}";

            $.ajaxSetup({
                beforeSend: function(xhr, settings) {
                    if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrf_token);
                    }
                }
            });
             $.ajax({
                 url: "{{ url_for('frontend.delete_ext') }}",
                 method: "POST",
                 contentType: "application/json",
                 dataType: 'json',
                 data: JSON.stringify( {"extensionCode": extensionCode})
             });
         }
 </script>
{%- endblock %}

flask_app/templates/extension_details.html
{# This simple template derives from ``base.html``. See ``base.html`` for
    more information about template inheritance. #}
 {%- extends "base.html" %}
 
 {# Loads some of the macros included with Flask-Bootstrap. We are using the
    utils module here to automatically render Flask's flashed messages in a
    bootstrap friendly manner #}
 {% import "bootstrap/utils.html" as utils %}
 
 {% block styles -%}
 {{super()}} 
 <link rel="stylesheet" type="text/css"
       href="{{url_for('static', filename='styles/extensions.css')}}">
{% endblock %}

 
 {# Inside the ``content`` is where you should place most of your own stuff.
    This will keep scripts at the page end and a navbar you add on later
    intact. #}
 {% block content %}

 <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
 <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

 <div class="container">
    <p>Pokemon extension: {{ext_name}}, Code: {{ ext_code }}</p>
     <button type="button" class="btn btn-delete" onclick="deleteExtension('{{ ext_code }}')">
        Delete this extension
    </button>
    <div class="row">
       <div>
          <!-- Adding bootstrap table classes to style a table-->
          <table class="table table-hover table-striped text-center">
             <thead>
                <tr>
                   <th scope="col">Number</th>
                   <th scope="col">Name</th>
                    <th scope="col">Japanese Name</th>
                </tr>
             </thead>

             <tbody class="text-left">
               {% for odx, row in ext.iterrows() %}
               <tr>
                   <td> <a class="btn" rel="popover" data-img={{ row['cardImageUrl'] }}> {{ row['cardNumber'] }} </a></td>
                   {% if row['owned'] %}
                   <td><input type="checkbox" name="id" onChange="handleChange(this, '{{ row['cardName'] }}', {{ row['cardNumber'] }}, '{{ ext_code }}')" checked> {{ row['cardName'] }}</td>
                   {% else %}
                   <td><input type="checkbox" name="id" onChange="handleChange(this, '{{ row['cardName'] }}', {{ row['cardNumber'] }}, '{{ ext_code }}')"> {{ row['cardName'] }}</td>
                   {% endif %}
                   <td> <p>{{ row['cardJapaneseName'] }}</p></td>
               </tr>
               {% endfor %}
             </tbody>
          </table>
          <button type="button" value="selectAll" class="main" onclick="checkAll()">Select All</button>
          <button type="button" value="deselectAll" class="main" onclick="uncheckAll()">Clear</button>
       </div>
    </div>
 </div>
 <div>
   <p>&nbsp;</p> 
   <p>&nbsp;</p> 
   <p>&nbsp;</p> 
 </div>

 
<script>
   $('a[rel=popover]').popover({
   html: true,
   trigger: 'hover',
   placement: 'auto right',
   content: function(){return '<img src="'+$(this).data('img') + '" style="width:360px;height:500px;"/>';}
   });
</script>

<script type="text/javascript" src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
 <script type="text/javascript">
    // Select all check boxes : Setting the checked property to true in checkAll() function
    function checkAll(){
      var items = document.getElementsByName('id');
        for (var i = 0; i < items.length; i++) {
            if (items[i].type == 'checkbox' && items[i].checked == false)
                items[i].click();
        }
    }
  // Clear all check boxes : Setting the checked property to false in uncheckAll() function
    function uncheckAll(){
      var items = document.getElementsByName('id');
        for (var i = 0; i < items.length; i++) {
            if (items[i].type == 'checkbox' && items[i].checked == true)
               items[i].click();
        }
    }

      function handleChange(sel, cardName, cardNumber, cardExtensionCode){
            var csrf_token = "{{ csrf_token() }}";

            $.ajaxSetup({
                beforeSend: function(xhr, settings) {
                    if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrf_token);
                    }
                }
            });
             $.ajax({
                 url: "{{ url_for('frontend.data_post') }}",
                 method: "POST",
                 contentType: "application/json",
                 dataType: 'json',
                 data: JSON.stringify( {"cardName": cardName, "cardNumber": cardNumber, "cardExtensionCode": cardExtensionCode, "owned": sel.checked})
             });
         }

      function deleteExtension(extensionCode){
            var csrf_token = "{{ csrf_token() }}";

            $.ajaxSetup({
                beforeSend: function(xhr, settings) {
                    if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrf_token);
                    }
                }
            });
             $.ajax({
                 url: "{{ url_for('frontend.delete_ext') }}",
                 method: "POST",
                 contentType: "application/json",
                 dataType: 'json',
                 data: JSON.stringify( {"extensionCode": extensionCode})
             });
         }
 </script>

 {%- endblock %}

flask_app/templates/extension_page.html
{# This simple template derives from ``base.html``. See ``base.html`` for
more information about template inheritance. #}
{%- extends "base.html" %}

{# Loads some of the macros included with Flask-Bootstrap. We are using the
utils module here to automatically render Flask's flashed messages in a
bootstrap friendly manner #}
{% import "bootstrap/utils.html" as utils %}

{% block styles -%}
{{super()}}
<link rel="stylesheet" type="text/css"
      href="{{url_for('static', filename='styles/extensions.css')}}">
{% endblock %}


{# Inside the ``content`` is where you should place most of your own stuff.
This will keep scripts at the page end and a navbar you add on later
intact. #}
{% block content %}
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script>
$(document).ready(function(){
  load_data();
  function load_data(query)
  {
  var csrf_token = "{{ csrf_token() }}";

    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrf_token);
            }
        }
    });
   $.ajax({
    url: "{{ url_for('frontend.extension_live_search') }}",
    method:"POST",
    data:{'query': query},
    success:function(data)
    {
      $('#result').html(data);
      $("#result").append(data.htmlresponse);
    }
   });
  }
  $('#search_text').keyup(function(){
    var search = $(this).val();
    load_data(search);
  });
});
</script>

<div class="search-box">
    <div class="row">
        <div class="col-md-8 search-div">
            <h5>Search Extensions</h5>
        </div>
        <div class="col-md-8 search-div">
            <input type="text" name="search_text" id="search_text" class="form-control" placeholder="Search any extensions (code or name)">
        </div>
    </div>
</div>
<div id="result"></div>
{%- endblock %}

flask_app/templates/options.html
{# This simple template derives from ``base.html``. See ``base.html`` for
more information about template inheritance. #}
{%- extends "base.html" %}

{# Loads some of the macros included with Flask-Bootstrap. We are using the
utils module here to automatically render Flask's flashed messages in a
bootstrap friendly manner #}
{% import "bootstrap/utils.html" as utils %}

{% block styles -%}
{{super()}}
<link rel="stylesheet" type="text/css"
      href="{{url_for('static', filename='styles/options.css')}}">
{% endblock %}

{# Inside the ``content`` is where you should place most of your own stuff.
This will keep scripts at the page end and a navbar you add on later
intact. #}

{% block content %}

<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"/>
<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script>
// function to log the output
      $(document).ready(function(){
        var output_extensions = document.getElementById('output-extensions');
        var output_cards = document.getElementById('output-cards');

        var xhr_extensions = new XMLHttpRequest();
        if (window.countIntervalExt) clearInterval(window.countIntervalExt)
        xhr_extensions.open('GET', '{{ url_for('frontend.log_extensions_stream') }}', true);
        xhr_extensions.send();
        window.countIntervalExt = setInterval(function() {
          output_extensions.textContent = xhr_extensions.responseText;
        }, 500);

        var xhr_cards = new XMLHttpRequest();
        if (window.countIntervalCard) clearInterval(window.countIntervalCard)
        xhr_cards.open('GET', '{{ url_for('frontend.log_cards_stream') }}', true);
        xhr_cards.send();
        window.countIntervalCard = setInterval(function() {
          output_cards.textContent = xhr_cards.responseText;
        }, 500);

      });



</script>

<script type=text/javascript>
      function fetch_extensions() {
            var csrf_token = "{{ csrf_token() }}";

            $.ajaxSetup({
                beforeSend: function(xhr, settings) {
                    if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrf_token);
                    }
                }
            });
            document.getElementById('extensions-button').disabled = true;
            setTimeout(function(){ document.getElementById("extensions-button").disabled = false; },50000);
            $.ajax({
                 url: "{{ url_for('frontend.launch_fetching_extensions') }}",
                 method: "POST"
             });
       }

       function fetch_cards() {
            var csrf_token = "{{ csrf_token() }}";

            $.ajaxSetup({
                beforeSend: function(xhr, settings) {
                    if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrf_token);
                    }
                }
            });
            document.getElementById('cards-button').disabled = true;
            setTimeout(function(){ document.getElementById("cards-button").disabled = false; },50000);
            $.ajax({
                 url: "{{ url_for('frontend.launch_fetching_cards') }}",
                 method: "POST"
             });
       }


</script>

<div class="content">
{% with messages = get_flashed_messages(category_filter=["error"]) %}
  {% if messages %}
    <div class="alert">
    <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
    <strong>Danger!</strong> {{ get_flashed_messages(category_filter=["error"]) }}
    </div>
  {% endif %}
{% endwith %}

{% with messages = get_flashed_messages(category_filter=["success"]) %}
  {% if messages %}
    <div class="alert-success">
    <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
    <strong>Sucess!</strong> {{ get_flashed_messages(category_filter=["success"]) }}
    </div>
  {% endif %}
{% endwith %}

    <div>
        <button type="button" class="btnExt btn-primary" data-toggle="modal" data-target="#modalExt">
            Launch extensions fetching
        </button>
        <div class="modal fade" id="modalExt" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
             aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="modalExtLabel">Fetch extensions (please don't close)</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="logging_window">
                            <pre id="output-extensions"></pre>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button id="extensions-button" type="button" onclick="fetch_extensions()" class="btn btn-primary">
                            Fetch extensions
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div>
        <button type="button" class="btnCard btn-primary" data-toggle="modal" data-target="#modalCard">
            Launch cards fetching
        </button>

        <div class="modal fade" id="modalCard" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
             aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="modalCardLabel">Fetch cards (please don't close)</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="logging_window">
                            <pre id="output-cards"></pre>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button id="cards-button" type="button" onclick="fetch_cards()" class="btn btn-primary">Fetch
                            cards
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div>
        <button type="button" class="btnExport btn-primary"
                onclick="window.location.href='{{ url_for('frontend.export_data') }}';">Export your owned cards
        </button>
    </div>

    <div>
        <button type="button" class="btnImport btn-primary" data-toggle="modal" data-target="#modalCardImport">
            Put the file here to import your cards owned
        </button>

        <div class="modal fade" id="modalCardImport" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
             aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="modalCardImportLabel">Import your exported cards</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form class="form-inline center-block" action="{{ url_for('frontend.uploader') }}" method="POST" enctype="multipart/form-data">
                            {{ form.hidden_tag() }}
                            <div class="input-group">
                                <label id="browsebutton" class="btn btn-default input-group-addon" for="my-file-selector">
                                    {{ form.input_file(id="my-file-selector") }}
                                    Browse...
                                </label>
                                <input type="text" class="form-control" readonly>
                            </div>
                            {{ form.submit(class_="btn btn-primary") }}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{%- endblock %}

{% block scripts %}
{{ super() }}
<script src="{{ url_for('static', filename='js/inputFileButton.js') }}"></script>
{% endblock %}